# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking = {
    hostName = "ws";
    useDHCP = false;

    interfaces = {
       wlp0s20f3 = {
         useDHCP = true;
         name = "wlan0";
       };
       #enp0s20f0u11u1 = {
       #  useDHCP = true;
       #  name = "eth0";
       #};
       #enp0s20f0u13u1 = {
       #  useDHCP = true;
       #  name = "eth1";
       #};
    };
    wireless = {
      enable = true;
      interfaces = [ "wlan0" ];
      networks = {
        Desiyonan = {
          psk = "DnF_PDCN15987532";
        };
        DnF_WL = {
          psk = "DnF_WF15987532";
          priority = 1;
        };
        DnF_WL_5G = {
          psk = "DnF_WF15987532";
        };
      };
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7aaabf7b-8b28-4feb-b60a-81cb35968663";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/FA49-7E4A";
      fsType = "vfat";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FA49-7E4A";
      fsType = "vfat";
    };

 fileSystems."/data" =
   { device = "/dev/disk/by-uuid/09C1B27DA5EB573A";
     fsType = "ntfs-3g";
   };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e9a24aef-1fac-45ef-af49-aba05e2426f9"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
