;; Managed by NixOS (mesh/dotfs/uim)
(define custom-activate-default-im-name? #t)
(define custom-preserved-default-im-name 'py)
(define default-im-name 'py)
;; 仅保留简体拼音 + direct，避免 Ctrl+Space 在引擎间乱切
(define enabled-im-list '(py direct))
;; 关闭「切换引擎」；Ctrl+Space 留给开/关中文
(define enable-im-switch? #f)
(define switch-im-key '("<Control>Shift_key" "<Shift>Control_key"))
(define switch-im-key? (make-key-predicate '("<Control>Shift_key" "<Shift>Control_key")))
(define switch-im-skip-direct-im? #f)
(define enable-im-toggle? #f)
(define toggle-im-key '("<Meta> "))
(define toggle-im-key? (make-key-predicate '("<Meta> ")))
(define toggle-im-alt-im 'direct)
(define uim-color 'uim-color-uim)
(define candidate-window-style 'vertical)
(define candidate-window-position 'caret)
(define enable-lazy-loading? #t)
(define bridge-show-input-state? #f)
(define bridge-show-with? 'time)
(define bridge-show-input-state-time-length 3)
